### ISSUE TITLE
start: command not found

### ISSUE THREAD

**Issue by Coaxial** [TannerBaldus/getlucky#1]
Hey,

Trying to use GetLucky on OS X Mavericks and I always get `start: command not found`.

`$ gl genre metal
http://songza.com/listen/grindcore-s-death-trip-songza/: start: command not found`
`$ gl lucky -a
Get Down with your bad self
http://songza.com/listen/80s-hardcore-punk-boot-camp-david.wilentz/: start: command not found`

I used the tar.gz archive from https://pypi.python.org/pypi/GetLucky.

**Comment by TannerBaldus** [comment]
Shoulda closed this a while ago
